#!/bin/bash

./hashMultiPar 4096 +RTS -s 2> log
./hashMultiPar 8192 +RTS -s 2>> log
./hashMultiPar 16384 +RTS -s 2>> log
./hashMultiPar 32768 +RTS -s 2>> log
./hashMultiPar 65536 +RTS -s 2>> log

echo "Done"
